# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aaa3608fdd8321c857c367381fac7e21b4813a2f6a357afb45102436c4daf28f1940cc9baacbc39243005651586cbf748ae456f2fa65d2144ad8b4337a1d29ae

test:
  secret_key_base: 82ecebdce16f9e616b19ceb088bd706a76ef589b0166fd6835640efa616676e555be48dbc67710ffcc6943349c9367ab53abc356ddd65173301d91730084a2a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
